apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  DB_HOST: app-db.c1iuiewi0186.eu-north-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: app-db
  DJANGO_SETTINGS_MODULE: backend.settings
  ENV: production

